const actionTypes = {
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",

  GET_POSTS: "GET_POSTS",
  GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
  GET_LATEST_POSTS: "GET_LATEST_POSTS",

  GET_ALL_CATEGROIES: "GET_ALL_CATEGROIES",
  GET_ALL_PRICES: "GET_ALL_PRICES",
  GET_ALL_ACREAGES: "GET_ALL_ACREAGES",
  GET_ALL_PROVINCES: "GET_ALL_PROVINCES",

  // USER
  GET_CURRENT_USER: "GET_CURRENT_USER",
};

export default actionTypes;
